apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mon-secret
  namespace: poc-space
spec:
  vaultAuthRef: vault-auth
  mount: secret
  path: mon-app
  type: kv-v2
  refreshAfter: 1m          # Vérifie au moins toutes les 1 minute
  syncConfig:
    instantUpdates: true    # Active la synchro immédiate si Vault envoie des events
  destination:
    name: mon-secret        # Nom du Secret K8s à créer
    create: true            # Le crée s'il n'existe pas
    overwrite: true         # Écrase les valeurs existantes si elles changent