apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: poc-space
spec:
  address: "http://vault.vault.svc.cluster.local:8200"  # Adresse du service Vault
  skipTLSVerify: true   # ou false si TLS valide